name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        docker-files: ["chip", "matter-one"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build chip image
      run: docker build . --file ${{matrix.docker-files}} --tag ${{secrets.DOCKER_USER}}/esp-matter:${{matrix.docker-files}}
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker push
      run: |
        docker push ${{secrets.DOCKER_USER}}/esp-matter:${{matrix.docker-files}}
